name: Core

# This workflow is triggered on pushes or pull request to the repository.
on:
  push:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ci/**'
      - 'core/**'
      - '.github/workflows/core.yml'
      - '!**.md'
      - '!ci/jenkins/**'
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ci/**'
      - 'core/**'
      - '.github/workflows/core.yml'
      - '!**.md'
      - '!ci/jenkins/**'

jobs:
  build-images:
    name: Build Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch_type: ["cpu", "gpu"]
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Checkout Milvus
        uses: actions/checkout@v1
      - name: Docker Build
        shell: bash
        run: |
          docker build -t matrixji/milvus:1.1-cos-${{ matrix.arch_type }}-${{ steps.date.outputs.date }} -f Dockerfile.${{ matrix.arch_type }} .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push matrixji/milvus:1.1-cos-${{ matrix.arch_type }}-${{ steps.date.outputs.date }}

